version: '3'
services:
  app:
    container_name: app-renderer
    build: 
      context: services/app
      target: ssr # ssr | build
    image: build-app:latest
  proxy:
    container_name: nginx-proxy
    build:
      context: services/nginx
      target: development
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
      - 443:443/udp