version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      # target: build-app
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - ./games:/var/lib/transmission-daemon/games:rw