services:
  app:
    image: build-app:${VERSION_TAG}
    build: 
      context: services/app
      target: standalone
  proxy:
    image: app-proxy:${VERSION_TAG}
    build:
      context: services/nginx
      target: development
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
      - 443:443/udp