import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
	return (
		<html lang="en">
            <>
                <title>Create Next App</title>
                <meta name="descrption" content="Generated by create next app"/>
                <meta name="descrption" content="Generated by create next app"/>
				<meta name="theme-color" media="(prefers-color-scheme: light)" content="#f5e8fc" />
				<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#1B1A1F" />
				<meta name="color-scheme" content="dark light"/>
				<link rel="manifest" href="/manifest.json"/>
            </>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
